name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]  # atau "main", sesuaikan dengan branch default kamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
